CREATE TABLE IF NOT EXISTS pedidos (
  id     INT AUTO_INCREMENT PRIMARY KEY,
  correo VARCHAR(255) NOT NULL,
  items  TEXT         NOT NULL,
  total  DECIMAL(10,2) NOT NULL,
  fecha  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(50)  NOT NULL DEFAULT 'pendiente'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
